{% set name = "caf.space" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caf.space-{{ version }}.tar.gz
  sha256: ada45f4555eabc055d9d89d91723bb7fecaffa04ca4d4ed749e7b5944977d330

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools_scm
    - versioneer-518
    - pip
  run:
    - python >=3.9
    - caf.toolkit >=0.0.7
    - geopandas >=0.9
    - fiona >=1.8
    - shapely >=1.8
    - numpy >=1.21
    - pandas >=1.3
    - pydantic >=1.10.2
    - openpyxl >=3.0

test:
  imports:
    - caf.space
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Transport-for-the-North/caf.space
  summary: Easily generate translations between transport zoning systems
  dev_url: https://github.com/Transport-for-the-North/caf.space
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isaac-tfn
